package ru.ddsurok.datamodel;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MAlbum generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private int id;
     private User MUser;
     private String name;
     private String defaultcolor;
     private Set MPolygons = new HashSet(0);
     private Set MPoints = new HashSet(0);

    public Album() {
    }

	
    public Album(int id, User MUser, String name, String defaultcolor) {
        this.id = id;
        this.MUser = MUser;
        this.name = name;
        this.defaultcolor = defaultcolor;
    }
    public Album(int id, User MUser, String name, String defaultcolor, Set MPolygons, Set MPoints) {
       this.id = id;
       this.MUser = MUser;
       this.name = name;
       this.defaultcolor = defaultcolor;
       this.MPolygons = MPolygons;
       this.MPoints = MPoints;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getMUser() {
        return this.MUser;
    }
    
    public void setMUser(User MUser) {
        this.MUser = MUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDefaultcolor() {
        return this.defaultcolor;
    }
    
    public void setDefaultcolor(String defaultcolor) {
        this.defaultcolor = defaultcolor;
    }
    public Set getMPolygons() {
        return this.MPolygons;
    }
    
    public void setMPolygons(Set MPolygons) {
        this.MPolygons = MPolygons;
    }
    public Set getMPoints() {
        return this.MPoints;
    }
    
    public void setMPoints(Set MPoints) {
        this.MPoints = MPoints;
    }




}


