package ru.ddsurok.datamodel;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA



/**
 * MLine generated by hbm2java
 */
public class Line  implements java.io.Serializable {


     private int id;
     private Polygon MPolygon;
     private float x1;
     private float y1;
     private float x2;
     private float y2;

    public Line() {
    }

	
    public Line(int id, float x1, float y1, float x2, float y2) {
        this.id = id;
        this.x1 = x1;
        this.y1 = y1;
        this.x2 = x2;
        this.y2 = y2;
    }
    public Line(int id, Polygon MPolygon, float x1, float y1, float x2, float y2) {
       this.id = id;
       this.MPolygon = MPolygon;
       this.x1 = x1;
       this.y1 = y1;
       this.x2 = x2;
       this.y2 = y2;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Polygon getMPolygon() {
        return this.MPolygon;
    }
    
    public void setMPolygon(Polygon MPolygon) {
        this.MPolygon = MPolygon;
    }
    public float getX1() {
        return this.x1;
    }
    
    public void setX1(float x1) {
        this.x1 = x1;
    }
    public float getY1() {
        return this.y1;
    }
    
    public void setY1(float y1) {
        this.y1 = y1;
    }
    public float getX2() {
        return this.x2;
    }
    
    public void setX2(float x2) {
        this.x2 = x2;
    }
    public float getY2() {
        return this.y2;
    }
    
    public void setY2(float y2) {
        this.y2 = y2;
    }




}


