package ru.ddsurok.datamodel;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA



/**
 * MPoint generated by hbm2java
 */
public class Point  implements java.io.Serializable {


     private int id;
     private User MUser;
     private Album MAlbum;
     private float x;
     private float y;
     private String caption;
     private String color;

    public Point() {
    }

	
    public Point(int id, User MUser, float x, float y) {
        this.id = id;
        this.MUser = MUser;
        this.x = x;
        this.y = y;
    }
    public Point(int id, User MUser, Album MAlbum, float x, float y, String caption, String color) {
       this.id = id;
       this.MUser = MUser;
       this.MAlbum = MAlbum;
       this.x = x;
       this.y = y;
       this.caption = caption;
       this.color = color;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getMUser() {
        return this.MUser;
    }
    
    public void setMUser(User MUser) {
        this.MUser = MUser;
    }
    public Album getMAlbum() {
        return this.MAlbum;
    }
    
    public void setMAlbum(Album MAlbum) {
        this.MAlbum = MAlbum;
    }
    public float getX() {
        return this.x;
    }
    
    public void setX(float x) {
        this.x = x;
    }
    public float getY() {
        return this.y;
    }
    
    public void setY(float y) {
        this.y = y;
    }
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


