package ru.ddsurok.datamodel;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MPolygon generated by hbm2java
 */
public class Polygon  implements java.io.Serializable {


     private int id;
     private User MUser;
     private Album MAlbum;
     private String caption;
     private String color;
     private Set MLines = new HashSet(0);

    public Polygon() {
    }

	
    public Polygon(int id, User MUser) {
        this.id = id;
        this.MUser = MUser;
    }
    public Polygon(int id, User MUser, Album MAlbum, String caption, String color, Set MLines) {
       this.id = id;
       this.MUser = MUser;
       this.MAlbum = MAlbum;
       this.caption = caption;
       this.color = color;
       this.MLines = MLines;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getMUser() {
        return this.MUser;
    }
    
    public void setMUser(User MUser) {
        this.MUser = MUser;
    }
    public Album getMAlbum() {
        return this.MAlbum;
    }
    
    public void setMAlbum(Album MAlbum) {
        this.MAlbum = MAlbum;
    }
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getMLines() {
        return this.MLines;
    }
    
    public void setMLines(Set MLines) {
        this.MLines = MLines;
    }




}


