package ru.ddsurok.datamodel;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

/**
 * MSession generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private int authtoken;
     private User user;
     private Serializable id;
     private Date createtime;
     private Date lastupdatetime;
     private short livetime;

    public Session() {
    }

	
    public Session(int authtoken, User user, Date createtime, Date lastupdatetime, short livetime) {
        this.authtoken = authtoken;
        this.user = user;
        this.createtime = createtime;
        this.lastupdatetime = lastupdatetime;
        this.livetime = livetime;
    }
    public Session(int authtoken, User user, UUID id, Date createtime, Date lastupdatetime, short livetime) {
       this.authtoken = authtoken;
       this.user = user;
       this.id = id;
       this.createtime = createtime;
       this.lastupdatetime = lastupdatetime;
       this.livetime = livetime;
    }
   
    public int getAuthtoken() {
        return this.authtoken;
    }
    
    public void setAuthtoken(int authtoken) {
        this.authtoken = authtoken;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public Date getLastupdatetime() {
        return this.lastupdatetime;
    }
    
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }
    public short getLivetime() {
        return this.livetime;
    }
    
    public void setLivetime(short livetime) {
        this.livetime = livetime;
    }




}


