package ru.ddsurok.datamodel;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MUser generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String nick;
     private String hashpswd;
     private String family;
     private String name;
     private String email;
     private boolean islocked;
     private boolean isbaned;
     private Set MAlbums = new HashSet(0);
     private Set MPolygons = new HashSet(0);
     private Set MPoints = new HashSet(0);
     private Set MSessions = new HashSet(0);

    public User() {
    }
    
    
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append(String.format("USER [ %d ]\n", this.getId()));
        builder.append("{\n");
        builder.append(String.format("\tNICK: %s;\n", this.getNick()));
        builder.append(String.format("\tNAME: %s %s;\n", this.getFamily(), this.getName()));
        builder.append(String.format("\tE-MAIL: %s;\n", this.getEmail()));
        builder.append(String.format("\tIS LOCKED: %s;\n", Boolean.toString(islocked)));
        builder.append(String.format("\tIS BANED: %s;\n", Boolean.toString(isbaned)));
        builder.append("}\n");
        return builder.toString();
    }
	
    public User(int id, String nick, String hashpswd, String email, boolean islocked, boolean isbaned) {
        this.id = id;
        this.nick = nick;
        this.hashpswd = hashpswd;
        this.email = email;
        this.islocked = islocked;
        this.isbaned = isbaned;
    }
    
    public User(int id, String nick, String hashpswd, String family, String name, String email, boolean islocked, boolean isbaned, Set MAlbums, Set MPolygons, Set MPoints, Set MSessions) {
       this.id = id;
       this.nick = nick;
       this.hashpswd = hashpswd;
       this.family = family;
       this.name = name;
       this.email = email;
       this.islocked = islocked;
       this.isbaned = isbaned;
       this.MAlbums = MAlbums;
       this.MPolygons = MPolygons;
       this.MPoints = MPoints;
       this.MSessions = MSessions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    
    public String getHashpswd() {
        return this.hashpswd;
    }
    
    public void setHashpswd(String hashpswd) {
        this.hashpswd = hashpswd;
    }
    
    public String getFamily() {
        return this.family;
    }
    
    public void setFamily(String family) {
        this.family = family;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public boolean isIslocked() {
        return this.islocked;
    }
    
    public void setIslocked(boolean islocked) {
        this.islocked = islocked;
    }
    
    public boolean isIsbaned() {
        return this.isbaned;
    }
    
    public void setIsbaned(boolean isbaned) {
        this.isbaned = isbaned;
    }
    
    public Set getMAlbums() {
        return this.MAlbums;
    }
    
    public void setMAlbums(Set MAlbums) {
        this.MAlbums = MAlbums;
    }
    
    public Set getMPolygons() {
        return this.MPolygons;
    }
    
    public void setMPolygons(Set MPolygons) {
        this.MPolygons = MPolygons;
    }
    
    public Set getMPoints() {
        return this.MPoints;
    }
    
    public void setMPoints(Set MPoints) {
        this.MPoints = MPoints;
    }
    
    public Set getMSessions() {
        return this.MSessions;
    }
    
    public void setMSessions(Set MSessions) {
        this.MSessions = MSessions;
    }
}


