package ru.ddsurok.datamodel.db;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA

import ru.ddsurok.datamodel.ws.XYPoint;


/**
 * MLine generated by hbm2java
 */
public class GeometricPoint extends XYPoint implements java.io.Serializable {

    private int Id;
    
    public GeometricPoint() {
        this.X = 0;
        this.Y = 0;
    }
    
    public GeometricPoint(XYPoint p) {
        this.X = p.X;
        this.Y = p.Y;
    }

    public GeometricPoint(int id, float x, float y) {
        this.Id = id;
        this.X = x;
        this.Y = y;
    }

    public int getId() {
        return this.Id;
    }

    public void setId(int id) {
        this.Id = id;
    }

    public float getX() {
        return this.X;
    }

    public void setX(float x1) {
        this.X = x1;
    }

    public float getY() {
        return this.Y;
    }

    public void setY(float y1) {
        this.Y = y1;
    }
}
