package ru.ddsurok.datamodel.db;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA

import ru.ddsurok.datamodel.ws.XYPoint;


/**
 * MPoint generated by hbm2java
 */
public class Mark extends XYPoint implements java.io.Serializable {

    private int Id;
    private User Author;
    private String Caption;
    private String Color;

    public Mark() {
        this.X = 0;
        this.Y = 0;
    }

    public Mark(int id, User MUser, float x, float y) {
        this.Id = id;
        this.Author = MUser;
        this.X = x;
        this.Y = y;
        this.X = 0;
        this.Y = 0;
    }

    public Mark(int id, User MUser, Album MAlbum, float x, float y, String caption, String color) {
        this.Id = id;
        this.Author = MUser;
        this.X = x;
        this.Y = y;
        this.Caption = caption;
        this.Color = color;
        this.X = 0;
        this.Y = 0;
    }

    public int getId() {
        return this.Id;
    }

    public void setId(int id) {
        this.Id = id;
    }

    public User getAuthor() {
        return this.Author;
    }

    public void setAuthor(User MAuthor) {
        this.Author = MAuthor;
    }

    public String getCaption() {
        return this.Caption;
    }

    public void setCaption(String caption) {
        this.Caption = caption;
    }

    public String getColor() {
        return this.Color;
    }

    public void setColor(String color) {
        this.Color = color;
    }
}
