package ru.ddsurok.datamodel.db;


// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

/**
 * MSession generated by hbm2java
 */
public class Session implements java.io.Serializable {

    private long AuthToken;
    private User User;
    private UUID Id;
    private Date CreateTime;
    private Date LastUpdateTime;
    private short LiveTime;

    public Session() {
        this.Id = UUID.randomUUID();
        this.CreateTime = new Date();
        this.LastUpdateTime = new Date();
    }

    public Session(long authtoken, User user, short livetime) {
        this.AuthToken = authtoken;
        this.User = user;
        this.Id = UUID.randomUUID();
        this.CreateTime = new Date();
        this.LastUpdateTime = new Date();
        this.LiveTime = livetime;
    }
    
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder("SESSION [ ");
        builder.append(this.Id.toString()).append(" ]\n");
        builder.append("{\n");
        builder.append("\tAUTHTOKEN: ").append(this.AuthToken).append(";\n");
        builder.append("\tUSER: ").append(this.User.getNick()).append(";\n");
        builder.append("\tCREATE: ").append(this.CreateTime).append(";\n");
        builder.append("\tUPDATE: ").append(this.LastUpdateTime).append(";\n");
        builder.append("\tLEAVETIME: ").append(this.LiveTime).append("\n");
        builder.append("}\n");
        return builder.toString();
    }

    public long getAuthToken() {
        return this.AuthToken;
    }

    public void setAuthToken(long authtoken) {
        this.AuthToken = authtoken;
    }

    public User getUser() {
        return this.User;
    }

    public void setUser(User user) {
        this.User = user;
    }

    public String getId() {
        return Id.toString();
    }

    public void setId(String id) {
        this.Id = UUID.fromString(id);
    }

    public Date getCreateTime() {
        return this.CreateTime;
    }

    public void setCreateTime(Date createtime) {
        this.CreateTime = createtime;
    }

    public Date getLastUpdateTime() {
        return this.LastUpdateTime;
    }

    public void setLastUpdateTime(Date lastupdatetime) {
        this.LastUpdateTime = lastupdatetime;
    }

    public short getLiveTime() {
        return this.LiveTime;
    }

    public void setLiveTime(short livetime) {
        this.LiveTime = livetime;
    }
}
