package ru.ddsurok.datamodel.db;
// Generated 19.12.2012 13:07:07 by Hibernate Tools 3.2.1.GA

import ru.ddsurok.utils.UserUtil;

/**
 * MUser generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int id;
    private String nick;
    private String hashpswd;
    private String family;
    private String name;
    private String email;
    private boolean islocked;
    private boolean isbaned;

    public User() {
//        this.Points = new HashSet(0);
//        this.Sessions = new HashSet(0);
//        this.CompositeObjects = new HashSet(0);
//        this.Albums = new HashSet(0);
    }

    public User(String nick, String hashpswd, String email, boolean islocked, boolean isbaned) {
//        this.Points = new HashSet(0);
//        this.Sessions = new HashSet(0);
//        this.CompositeObjects = new HashSet(0);
//        this.Albums = new HashSet(0);
        this.nick = nick;
        this.hashpswd = hashpswd;
        this.email = email;
        this.islocked = islocked;
        this.isbaned = isbaned;
    }

    public User(String nick, String hashpswd, String family, String name, String email, boolean islocked, boolean isbaned) {
        this.nick = nick;
        this.hashpswd = hashpswd;
        this.family = family;
        this.name = name;
        this.email = email;
        this.islocked = islocked;
        this.isbaned = isbaned;
//        this.Albums = MAlbums;
//        this.CompositeObjects = MCompositeObjects;
//        this.Points = MPoints;
//        this.Sessions = MSessions;
    }
    
    public User(String user) {
        UserUtil util = new UserUtil();
        util.getUserByNick(user);
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append(String.format("USER [ %d ]\n", this.getId()));
        builder.append("{\n");
        builder.append(String.format("\tNICK: %s;\n", this.getNick()));
        builder.append(String.format("\tNAME: %s %s;\n", this.getFamily(), this.getName()));
        builder.append(String.format("\tE-MAIL: %s;\n", this.getEmail()));
        builder.append(String.format("\tIS LOCKED: %s;\n", Boolean.toString(islocked)));
        builder.append(String.format("\tIS BANED: %s;\n", Boolean.toString(isbaned)));
        builder.append("}\n");
        return builder.toString();
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNick() {
        return this.nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getHashpswd() {
        return this.hashpswd;
    }

    public void setHashpswd(String hashpswd) {
        this.hashpswd = hashpswd;
    }

    public String getFamily() {
        return this.family;
    }

    public void setFamily(String family) {
        this.family = family;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isIslocked() {
        return this.islocked;
    }

    public void setIslocked(boolean islocked) {
        this.islocked = islocked;
    }

    public boolean isIsbaned() {
        return this.isbaned;
    }

    public void setIsbaned(boolean isbaned) {
        this.isbaned = isbaned;
    }
}
